build:
  project: VkNet.sln
  verbosity: minimal
  publish_nuget: true
version: '1.34.0-alpha{build}'
configuration:
- Release
platform: Any CPU
before_build:
- appveyor-retry dotnet restore -v Minimal
- nuget restore
build_script:
- dotnet msbuild "VkNet.sln" -c %CONFIGURATION% --no-dependencies
after_build:
- dotnet pack "VkNet\VkNet.csproj" -c %CONFIGURATION% --no-build -o artifacts
test_script:
- dotnet test "VkNet.Tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
cache:
- '%USERPROFILE%\.nuget\packages'
